name: gaggle
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.6.2
  - numpy=1.23.5
  - numpy-base=1.23.5
  - pip=22.3.1
  - python=3.10.9
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pyyaml=6.0
  - setuptools=65.6.3
  - six=1.16.0
  - tokenizers=0.11.4
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - transformers=4.26.1
  - pip:
    - pyqt5-sip==12.11.0
